repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.11.2"
    hooks:
      - id: uv-lock
      - id: uv-sync
      - id: uv-export
        args: ["--frozen", "--output-file=requirements-dev.txt"]
      - id: uv-export
        args:
          ["--frozen", "--no-default-groups", "--output-file=requirements.txt"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/ikamensh/flynt/
    rev: "1.0.6"
    hooks:
      - id: flynt
