from collections.abc import Callable
from typing import Any

def try_for(fn: Callable[[], Any], timeout: float = 5.0, delay: float = 0.1) -> Any: ...

class LockBase:
    fd: int | None
    filename: str
    locked: bool

    def __init__(self, filename: str) -> None: ...
    def __del__(self) -> None: ...
    def acquire(self, blocking: bool = False) -> bool: ...
    def release(self) -> None: ...

class FcntlLock(LockBase):
    def acquire(self, blocking: bool = False) -> bool: ...
    def release(self) -> None: ...

class MsvcrtLock(LockBase):
    def acquire(self, blocking: bool = False) -> bool: ...
    def release(self) -> None: ...

class FileLock(LockBase):
    def acquire(self, blocking: bool = False) -> bool: ...
    def release(self) -> None: ...
